### ISSUE TITLE
Heat pipe capacity not enough

### ISSUE THREAD

**Issue by black3agl3** [DanielWinks/Factorio-Advanced-Electric#2]
I was testing a few things and it seems to me that the generic heat pipe throughput isn't enough to bring all the heat from the nuclear reactor mk2 to the heat exchangers.

Let's assume we have an infinitely long dual row of nuclear reactors. The edges become insignificant and each reactor is surrounded by 3 others, for a 300% bonus
Each reactor mk2 will output 120 + 120 *3 = 480 MW of power.

1 Heat exchanger mk 2 uses 30 MW of power
We need 480 / 30 = 16 heat exchangers per reactor.

So i tried putting 16 exchangers on one single line of heat pipe with 2 nuclear reactors to simulate the 480 MW as you can see here
![image](https://user-images.githubusercontent.com/7523386/39663526-fd0dc45e-5042-11e8-82b4-8b56814b20b4.png)
2 reactors would both have 100% bonus so it is (120 base + 120 bonus) * 2 = 480 MW, which is what each reactor would output on its on in an ideal case.

So I ran into the problem where the temperature wasn't enough about halfway down the line to actually power the heat exchangers and i had a total power output of about 250 something MW instead of the expected 480 MW

I tried modifying the heat pipe max_temperature to 1200 to match the nuclear reactor and it did help some but it wasn't enough on its own.

At some point i tried to change the max temp of the nuclear reactor and the heat pipe to 3000 just to see what would happen and it kinda worked but that was ugly so i reverted the change.

After that i tried changing the specific_heat from 1MJ to 3MJ just to see what would happen and it came very close to actually having enough throughput to power all the heat exchangers. i had about 400 MW of power, so about 13 heat exchangers were powered properly.

Tripling the specific heat comes very close to being enough because the nuclear reactor itself outputs 3 times as much heat compared to the vanilla reactor but the problem is that the heat exchangers require 750 degrees before they start to work compared to the vanilla 500, so we kinda have to adjust the max temp of the heat pipe too.

I think changing the max temp to 1200 and specific heat to 3MJ is the right call. Or maybe add a new heat pipe mk2 with those stats? Idk, i'll leave the decision to you.

with those changes i got a perfect 480 MW once everything stabilised.
![image](https://user-images.githubusercontent.com/7523386/39663721-7cb8dc9a-5046-11e8-8dc9-72b5a26b73b6.png)

**Comment by DanielWinks** [comment]
Excellent. Having recently purchased a house that needs a lot of work, I haven't had much time to play. I'll work on getting these updates added as a heat pipe mk2, as I don't want to possibly change the balance of the mk1 stock pipes.

**Comment by DanielWinks** [comment]
Updated to include heat pipe mk2 as per above testing. Uploaded new version to Factorio Mods portal.
